### ISSUE TITLE
Convert template to spring boot(add template to springboost with thymeleaf)

### ISSUE THREAD

**Issue by minhhiennn** [minhhiennn/ProjectAnToanCuoiKy#4]
Page must done in this weekend:
- Home --> assignment: Tường
- SignIn --> assignment: Phùng
- SignUp --> assignment: Phùng
- ProductList --> assignment: Hiển
- Product --> assignment: Hiển
- CartItemList --> assignment: Tường

**Comment by tranmanhtuong123** [comment]
:'(

**Comment by phungle2508** [comment]
OK

**Comment by phungle2508** [comment]
commit uploaded

**Comment by minhhiennn** [comment]
Done!
